config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :bank_accounts, except: [ :show ] do
    get 'delete', on: :member
  end

  resources :operations, except: [ :show ]

  resources :tags, except: [ :show ]

  root to: 'dashboard#index'
end

app/models/tag.rb
class Tag < ApplicationRecord
  multi_tenant :user

  validates :name, presence: true, uniqueness: true

  default_scope -> { order(:name) }
end

app/controllers/tags_controller.rb
class TagsController < TenantController
  before_action :set_tag, only: %i[ edit update destroy ]

  def index
    @tags = Tag.all

    respond_with @tags
  end

  def new
    @tag = Tag.new

    respond_with @tag
  end

  def edit
    respond_with @tag
  end

  def create
    @tag = Tag.create tag_params

    respond_with @tag, location: -> { tags_url }
  end

  def update
    @tag.update tag_params

    respond_with @tag, location: -> { tags_url }
  end

  def destroy
    @tag.destroy

    respond_with @tag, location: -> { tags_url }
  end

  private
    def set_tag
      @tag = Tag.find params[:id]
    end

    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/views/tags/_form.html.haml
= simple_form_for tag do |f|
  = f.error_notification

  = f.input :name

  = form_actions f, cancel_url: tags_path

app/views/tags/_tag.html.haml
%tr[tag]
  %td= tag.name
  %td.table-actions
    = link_to_edit edit_tag_path(tag)
    = link_to_destroy tag_path(tag)

app/views/tags/edit.html.haml
%h1= t '.title'

= render 'form', tag: @tag

app/views/tags/index.html.haml
= page_title do
  %h1= t '.title'
  = button_new new_tag_path

= display_when_present @tags do
  %table.table
    %thead
      %tr
        %th= Tag.human_attribute_name :name
        %th.table-actions

    %tbody= render @tags

app/views/tags/new.html.haml
%h1= t '.title'

= render 'form', tag: @tag