config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :bank_accounts, except: [ :show ] do
    get 'delete', on: :member
  end

  resources :operations, except: [ :show ]

  resources :tags, except: [ :show ]

  root to: 'dashboard#index'
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  multi_tenant :user

  has_many :operations

  validates :name, presence: true, uniqueness: true

  default_scope -> { order(:name) }

  def destroy_and_replace! form
    if form.valid?
      operations.update_all bank_account_id: form.replace_id

      self.destroy
    else
      self.errors.add :base, :invalid
    end
  end
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < TenantController
  before_action :set_bank_account, only: %i[ edit update delete destroy ]

  def index
    @bank_accounts = BankAccount.all

    respond_with @bank_accounts
  end

  def new
    @bank_account = BankAccount.new

    respond_with @bank_account
  end

  def edit
    respond_with @bank_account
  end

  def create
    @bank_account = BankAccount.create bank_account_params

    respond_with @bank_account, location: -> { bank_accounts_url }
  end

  def update
    @bank_account.update bank_account_params

    respond_with @bank_account, location: -> { bank_accounts_url }
  end

  def delete
    @bank_account_delete_form = BankAccountDeleteForm.new

    respond_with @bank_account
  end

  def destroy
    @bank_account_delete_form = BankAccountDeleteForm.new bank_account_delete_params

    @bank_account.destroy_and_replace! @bank_account_delete_form

    respond_with @bank_account, action: :delete, location: -> { bank_accounts_url }
  end

  private
    def set_bank_account
      @bank_account = BankAccount.find params[:id]
    end

    def bank_account_params
      params.require(:bank_account).permit(:name)
    end

    def bank_account_delete_params
      params.require(:bank_account_delete_form).permit(:replace_id)
    end
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper

  def bank_accounts_collection except_ids: nil
    bank_accounts = BankAccount.all

    bank_accounts = bank_accounts.where.not(id: except_ids) if except_ids.present?

    bank_accounts
  end

end

app/views/bank_accounts/_bank_account.html.haml
%tr[bank_account]
  %td= bank_account.name
  %td.table-actions
    = link_to_edit edit_bank_account_path(bank_account)

    - if @bank_accounts.count > 1
      = link_to_delete delete_bank_account_path(bank_account)

app/views/bank_accounts/_form.html.haml
= simple_form_for bank_account do |f|
  = f.error_notification

  = f.input :name

  = form_actions f, cancel_url: bank_accounts_path

app/views/bank_accounts/delete.html.haml
%h1= t '.title'

= simple_form_for @bank_account_delete_form, url: bank_account_path(@bank_account), method: 'delete' do |f|
  = f.error_notification

  %h2= @bank_account.name

  = f.input :replace_id, collection: bank_accounts_collection(except_ids: @bank_account.id), include_blank: false

  = form_actions f, cancel_url: bank_accounts_path, button_html: { class: 'btn-danger' }, button_text: t('text.destroy')

app/views/bank_accounts/edit.html.haml
%h1= t '.title'

= render 'form', bank_account: @bank_account

app/views/bank_accounts/index.html.haml
= page_title do
  %h1= t '.title'
  = button_new new_bank_account_path

= display_when_present @bank_accounts do
  %table.table
    %thead
      %tr
        %th= BankAccount.human_attribute_name :name
        %th.table-actions

    %tbody= render @bank_accounts

app/views/bank_accounts/new.html.haml
%h1= t '.title'

= render 'form', bank_account: @bank_account