config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :bank_accounts, except: [ :show ] do
    get 'delete', on: :member
  end

  resources :operations, except: [ :show ]

  resources :tags, except: [ :show ]

  root to: 'dashboard#index'
end

app/models/operation.rb
class Operation < ApplicationRecord
  include I18n::Alchemy

  multi_tenant :user

  belongs_to :bank_account

  has_and_belongs_to_many :tags

  validates :description, presence: true
  validates :due_at     , presence: true

  before_save :set_amount_by_flow_in

  default_scope -> { order(:due_at) }

  def amount
    (@amount || original_amount).to_f.abs
  end

  def original_amount
    read_attribute :amount
  end

  private
    def set_amount_by_flow_in
      write_attribute :amount, amount * (flow_in? ? 1 : -1)
    end
end

app/controllers/operations_controller.rb
class OperationsController < TenantController
  before_action :set_operation, only: [ :edit, :update, :destroy ]

  respond_to :html

  def index
    @date = begin
        Date.parse params[:date]
    rescue
      Date.today
    end

    @paid = params.fetch(:paid, false) == 'true'

    @operations = Operation.where('due_at between ? and ?', @date.beginning_of_month, @date.end_of_month).where(paid: @paid).all

    @operations_flow_in_total  = @operations.where(flow_in: true).sum(:amount)
    @operations_flow_out_total = @operations.where(flow_in: false).sum(:amount).abs
    @operations_total = @operations.sum(:amount)

    respond_with @operations
  end

  def new
    @operation = Operation.new

    respond_with @operation
  end

  def edit
  end

  def create
    @operation = Operation.new
    @operation.localized operation_params
    @operation.save

    respond_with @operation, location: -> { operations_url }
  end

  def update
    @operation.localized operation_params
    @operation.save

    respond_with @operation, location: -> { operations_url }
  end

  def destroy
    @operation.destroy

    respond_with @operation, location: -> { operations_url }
  end

  private
    def set_operation
      @operation = Operation.find params[:id]
    end

    def operation_params
      params.require(:operation).permit(:flow_in, :description, :amount, :due_at, :paid, :bank_account_id, :comment, tag_ids: [])
    end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.haml
= simple_form_for operation.localized do |f|
  = f.error_notification

  = f.input :flow_in, as: :radio_buttons, collection: [ :true, :false ], wrapper: :vertical_collection_inline

  = f.input :description

  .row
    .col-sm= f.input :amount, as: :currency
    .col-sm= f.input :due_at, as: :date, html5: true, input_html: { value: operation.due_at }

  .row
    .col-sm= f.association :bank_account, include_blank: false, prompt: true
    .col-sm= f.input :paid, as: :radio_buttons, collection: [ :false, :true ], wrapper: :vertical_collection_inline

  = f.association :tags, as: :check_boxes, wrapper: :vertical_collection_inline

  = f.input :comment


  = form_actions f, cancel_url: operations_path

app/views/operations/_operation.html.haml
%tr[operation]
  %td= l operation.due_at
  %td= operation.description
  %td= operation.bank_account.name
  %td.text-end
    = n2c operation.amount if operation.flow_in?
  %td.text-end
    = n2c operation.amount if !operation.flow_in?
  %td.table-actions
    = link_to_edit edit_operation_path(operation)
    = link_to_destroy operation_path(operation)

app/views/operations/edit.html.haml
%h1= t '.title'

= render 'form', operation: @operation

app/views/operations/index.html.haml
= page_title do
  %h1= t '.title'
  = button_new new_operation_path

  .btn-group.ms-3{ role: 'group', 'aria-label': 'Navigation' }
    = link_to '<', operations_path(date: @date.prev_month, paid: @paid), class: 'btn btn-secondary'

    .dropdown.btn-group
      = button_tag class: "btn btn-secondary dropdown-toggle", id: 'dropdownNavigation', 'data-bs-toggle': 'dropdown', 'aria-expanded': 'false' do
        = l @date, format: :month

      %ul.dropdown-menu{ 'aria-labelledby': "dropdownNavigation" }
        %li= link_to t('text.current_month'), operations_path(date: Date.today, paid: @paid), class: 'dropdown-item'

    = link_to '>', operations_path(date: @date.next_month, paid: @paid), class: 'btn btn-secondary'



%ul.nav.nav-tabs
  %nav-item= link_to t('simple_form.options.operation.paid.false'), operations_path(date: @date, paid: false), class: "nav-link #{@paid ? '' : 'active'}"
  %nav-item= link_to t('simple_form.options.operation.paid.true'), operations_path(date: @date, paid: true), class: "nav-link #{@paid ? 'active' : ''}"


= display_when_present @operations do
  %table.table
    %thead
      %tr
        %th= Operation.human_attribute_name :due_at
        %th= Operation.human_attribute_name :description
        %th= Operation.human_attribute_name :bank_account
        %th.text-end= t 'simple_form.options.operation.flow_in.true'
        %th.text-end= t 'simple_form.options.operation.flow_in.false'
        %th.table-actions

    %tbody= render @operations

    %tfoot
      %tr.text-secondary
        %th{ colspan: 3 }
          Subtotal
        %th.text-end= n2c @operations_flow_in_total
        %th.text-end= n2c @operations_flow_out_total
        %th

      %tr
        %th{ colspan: 3 }
          Total
        %th.text-end{ colspan: 2 }
          = n2c @operations_total
        %th

app/views/operations/new.html.haml
%h1= t '.title'

= render 'form', operation: @operation